// <auto-generated />
using System;
using Alura.WebAPI.Model;
using Alura.WebAPI.WebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alura.WebAPI.WebApp.Migrations
{
    [DbContext(typeof(LeituraContext))]
    [Migration("20180601205523_Livros")]
    partial class Livros
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Alura.WebAPI.Model.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Capa")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Lista")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Resumo")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Livros");

                    b.HasData(
                        new { Id = 1, Autor = "J.K. Rowling", Lista = "ParaLer", Subtitulo = "E a Pedra Filosofal", Titulo = "Harry Potter 1" },
                        new { Id = 2, Autor = "J.K. Rowling", Lista = "ParaLer", Subtitulo = "E a Câmara Secreta", Titulo = "Harry Potter 2" },
                        new { Id = 3, Autor = "J.K. Rowling", Lista = "ParaLer", Subtitulo = "E o Prisioneiro de Askaban", Titulo = "Harry Potter 3" },
                        new { Id = 4, Autor = "J.K. Rowling", Lista = "ParaLer", Subtitulo = "E o Cálice Sagrado", Titulo = "Harry Potter 4" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
